spring:
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:backend/habitus-api/.env[.properties]
  application:
    name: ${APP_NAME:habitus-api}
  datasource:
    url: ${DATABASE_URL:jdbc:sqlite:data/habitus.db}
    driver-class-name: ${DATABASE_DRIVER:org.sqlite.JDBC}
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.community.dialect.SQLiteDialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}

server:
  port: ${SERVER_PORT:8080}
